media:
  input: static/images
  output: /images

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string

      - name: date
        label: Date
        type: date

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: body
        label: Body
        type: rich-text